### ISSUE TITLE
Helm: Add support for networking.k8s.io/v1

### ISSUE THREAD

**Issue by AlexanderBabel** [kubenav/deploy#8]
With Kubernetes v1.22.0 only `networking.k8s.io/v1` is supported. Therefore the helm chart should support the current version of the networking api.

In addition, support for `ingressClassName` should be added, because the old `kubernetes.io/ingress.class` annotation is deprecated. More information: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

Example for a new ingress class (source: https://github.com/longhorn/longhorn/blob/master/chart/templates/ingress.yaml):
```yaml
{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: {{ include "release_namespace" . }}
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-ingress
  annotations:
    {{- if .Values.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ default "" .Values.ingress.path }}
          {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: ImplementationSpecific
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: longhorn-frontend
              port:
                number: 80
            {{- else }}
            serviceName: longhorn-frontend
            servicePort: 80
            {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecret }}
{{- end }}
{{- end }}
```
